USE [ElectronicShop]
GO

INSERT INTO Cart VALUES (8, 1, 1);
INSERT INTO Cart VALUES (8, 2, 1);
INSERT INTO Cart VALUES (8, 3, 1);
INSERT INTO Cart VALUES (8, 4, 1);
INSERT INTO Cart VALUES (8, 5, 1);
INSERT INTO Cart VALUES (8, 6, 1);
INSERT INTO Cart VALUES (8, 7, 1);
INSERT INTO Cart VALUES (8, 8, 1);
INSERT INTO Cart VALUES (8, 9, 1);
INSERT INTO Cart VALUES (7, 12, 1);
INSERT INTO Cart VALUES (7, 13, 1);
INSERT INTO Cart VALUES (7, 16, 1);
INSERT INTO Cart VALUES (7, 19, 1);
INSERT INTO Cart VALUES (7, 20, 1);
INSERT INTO Cart VALUES (7, 25, 1);
INSERT INTO Cart VALUES (7, 26, 1);
INSERT INTO Cart VALUES (7, 29, 1);
INSERT INTO Cart VALUES (7, 30, 1);
INSERT INTO Cart VALUES (9, 31, 2);
INSERT INTO Cart VALUES (9, 32, 3);
INSERT INTO Cart VALUES (9, 33, 5);
INSERT INTO Cart VALUES (9, 34, 1);
INSERT INTO Cart VALUES (9, 35, 7);
INSERT INTO Cart VALUES (9, 38, 8);
